apiVersion: v1
kind: Secret
metadata:
  name: vault-postgres-secret
  namespace: vault
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
