apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: {{ .Values.vault.server.replicas }}
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: "{{ .Values.vault.server.image.repository }}:{{ .Values.vault.server.image.tag }}"
        ports:
        - containerPort: 8200
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: {{ .Values.vault.rootToken }}
        - name: VAULT_ADDR
          value: "http://0.0.0.0:8200"
        command: ["/bin/sh", "-c"]
        args:
          - vault server -config=/vault/config/vault.hcl
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
        - name: vault-data
          mountPath: /vault/data
      volumes:
      - name: vault-config
        configMap:
          name: vault-config
      - name: vault-data
        persistentVolumeClaim:
          claimName: vault-pvc
